/// <reference types="Cypress" />

describe("adds a todo and follows it", () => {
    it("adds a todo, marks it complete and marks it uncomplete", () => {
        const todo = "another todo"
        
        cy.visit("http://localhost:8888")
        cy.get('.new-todo')
            .click()
            .type(todo + "{enter}")
            .should("be.empty")
        cy.get(".todo-list")
            .should("contain", todo)
        cy.get('.todo-count')
            .should('contain', 1)
        cy.get(".todo-list > li .toggle")
            .eq(0)
            .check()
        cy.get('.todo-list > li')
            .eq(0)
            .should('have.class', 'completed')
        cy.get('.filters > li')
            .eq(2)
            .click()
            .url()
            .should('include', 'http://localhost:8888/#/completed')
        cy.get('.todo-list > li')
            .should('have.length', 1)
            .should('contain', todo)
        cy.get(".todo-list > li .toggle")
            .eq(0)
            .uncheck()
        cy.get('.todo-list')
            .should("not.be.visible")
        cy.get('.filters > li')
            .eq(0)
            .click()
            .url()
            .should('include', 'http://localhost:8888/#/')
        cy.get('.todo-list')
            .should("contain", todo)
    })
})